### PR TITLE
feat(ci): add release

### PR DESCRIPTION
**Pull request by pebie**

### CODE REVIEW

**Comment by tduyng** [comment]
We don't need create `.npmignore` file if it is empty, right?

And in `package.json` file, we've already specified `"files": ["/lib"],` for npm files, I think it's enough except that you want to ignore something else in this folder.

**Comment by pebie** [comment]
> 

Yes we do since `npm publish` ignore files within `.gitignore` files unless you add a `.npmignore` files. Thats why it is empty.

https://docs.npmjs.com/cli/v8/commands/npm-publish

**Comment by tienduy-nguyen** [comment]
Ah ok, for resolving the problem of folder: `lib`. Very good trick 👍

**Comment by tduyng** [comment]
> > 
> 
> Yes we do since `npm publish` ignore files within `.gitignore` files unless you add a `.npmignore` files. Thats why it is empty.
> 
> https://docs.npmjs.com/cli/v8/commands/npm-publish

Ah ok, for resolving the problem of folder: `lib`. Very good trick 👍

**Comment by tduyng** [comment]
I have just some small remarks. The rest looks ok for me. Thank @pebie for your contribution 🙏

**Pull request merged**
